### PR TITLE
fix: Add try/catch of occasional crash when parsing json

### LINKED ISSUE #241: SyntaxError JSON Parse error: Expected '}'
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.10.0
5.2.0
TechApp@1.8.0 /Users/esauter/Code/Peach/tech-app
├── camelcase@4.1.0
├── jwt-decode@2.1.0
├── lodash.debounce@4.0.8
├── lodash.startcase@4.4.0
├── moment@2.18.1
├── numeral@2.0.6
├── object.values@1.0.4
├── phone-formatter@0.0.2
├── qs@6.5.0
├── UNMET PEER DEPENDENCY react@16.0.0-rc.2
├── react-native@0.47.2
├── react-native-checkbox@1.2.0
├── react-native-code-push@5.0.0-beta
├── react-native-google-places-autocomplete@1.3.2
├── react-native-infinite-scroll-view@0.4.3
├── react-native-permissions@1.0.0
├── react-native-push-notification@3.0.1
├── react-native-segmented-control-tab@3.2.1
├── react-native-sentry@0.23.0
├── react-native-swipeout@2.1.5
├── react-native-tab-navigator@0.3.4
├── react-navigation@1.0.0-beta.11
├── react-redux@4.4.8
├── redux@3.7.2
├── redux-create-reducer@1.1.1
├── redux-logger@2.10.2
├── redux-thunk@2.2.0
├── reselect@2.5.4
├── rn-redux-mixpanel@1.1.9
├── semver@5.4.1
├── snakeize@0.1.0
├── underscore.string@3.3.4
├── us-dollars@1.0.1
└── uuid@3.1.0
```

Config:

```
  Sentry.config('https://KEY_HERE@sentry.io/TEAM_ID_HERE').install();

```

---
I have following issue:

I'm receiving a bunch of errors in sentry that seem to point to `node_modules/react-native-sentry/lib/NativeClient.js`. Specifically, the error is:

```
SyntaxError
JSON Parse error: Expected '}'
node_modules/react-native-sentry/lib/NativeClient.js in apply at line 63:40
    RNSentry.startWithDsnString(this._dsn);
    if (this.options.deactivateStacktraceMerging === false) {
      this._activateStacktraceMerging();
      const eventEmitter = new NativeEventEmitter(RNSentryEventEmitter);
      eventEmitter.addListener(RNSentryEventEmitter.MODULE_TABLE, moduleTable => {
        this._updateIgnoredModules(JSON.parse(moduleTable.payload)); // THIS IS LINE 63
      });
    }
    RNSentry.setLogLevel(options.logLevel);
  }
```

There's also a similar native error that references the module table, so they may be related:
```
EXC_BAD_ACCESS
Attempted to dereference garbage pointer 0x9e2bfbeb8.
Originated at or in a subcall of folly::Expected<long long, folly::ConversionCode> folly::detail::str_to_integral<long long>(folly::Range<char const*>*)
mach exception
EXC_BAD_ACCESS
signal
SIGBUS (10)
Fixt Partner
0x1005fdf18
+[RNSentryEventEmitter emitModuleTableUpdate:]
Called from:
Fixt Partner
__36-[RNSentry swizzleInvokeWithBridge:]_block_invoke_2
Fixt Partner
0x10056d2cc
facebook::react::RCTNativeModule::invokeInner(unsigned int, folly::dynamic const&&)
Fixt Partner
0x10056d138
___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke
```

**Steps to reproduce:**
- I haven't been able to reproduce this issue. I'm just seeing a lot of Sentry events. It says the error is fatal, but I haven't heard from users that they've been experiencing any issues. It seems to be occurring on a variety of iOS versions.

Thanks for any assistance you are able to provide!

### PR DESCRIPTION
**Pull request by HazAT**
Fixes #241

### CODE REVIEW

File: lib/NativeClient.js [hunk 1]
```diff
@@ -60,7 +60,11 @@ export class NativeClient {
       this._activateStacktraceMerging();
       const eventEmitter = new NativeEventEmitter(RNSentryEventEmitter);
       eventEmitter.addListener(RNSentryEventEmitter.MODULE_TABLE, moduleTable => {
-        this._updateIgnoredModules(JSON.parse(moduleTable.payload));
+        try {
+          this._updateIgnoredModules(JSON.parse(moduleTable.payload));
+        } catch (e) {
+          console.log(e);
```
Comment (mitsuhiko) [inline lib/NativeClient.js]: Remove the console.log and add a comment about why we think this happens.
