### PR TITLE
Native Android Support, Internal fixes and more ...

### LINKED ISSUE #37: Remove global dependency
The docs require sentry-cli be installed globally, but it would seem to be much preferable to make the cli a local dep and change the build script to:
```
../node_modules/.bin/sentry-cli react-native-xcode ../node_modules/react-native/packager/react-native-xcode.sh
../node_modules/.bin/sentry-cli upload-dsym
```

Any issues with this approach?

### PR DESCRIPTION
**Pull request by HazAT**
Depends on this to be merged: https://github.com/getsentry/raven-java/pull/381

- [x] https://github.com/facebook/react-native/blob/ea6845ca2275e0420761a087e6c8844ebaae343e/ReactAndroid/src/main/java/com/facebook/react/modules/core/ExceptionsManagerModule.java we want to catch js exceptions like on ios and send the on native
- [x] Fix breadcrumbs
- [x] Native crashes are not logged
- [x] Add native crash function
- [x] Do we need setExta/setTags ??
- [x] Fixes #37
- [x] Bump raven-js

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
hey @hazat thanks for your hard work on this! Can you give me a status on how far you currently are and how one may help you?

**Comment by HazAT** [comment]
Hey sorry for the delayed reply ... we are waiting for the release of version 8.0 of our raven-java client to integrate it fully into react-native.
The release should be this week, I will continue then, but hard to say how to help now ...

File: android/src/main/java/io/sentry/RNSentryModule.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ public void setTags(ReadableMap tags) {
 
     @ReactMethod
     public void setUser(ReadableMap user) {
-        Raven.getStoredInstance().getContext().setUser(
+        Sentry.getStoredClient().getContext().setUser(
```
Comment (bretthoerner) [inline android/src/main/java/io/sentry/RNSentryModule.java]: I'm going to add a `Sentry.setUser` method btw.

Comment (bretthoerner) [inline android/src/main/java/io/sentry/RNSentryModule.java]: Added on my branch (also `clearContext`): https://github.com/getsentry/raven-java/pull/378/commits/b6d2e1b908473e7b6f264e618089248d2fcd0dbe

**Comment by DanielMSchmidt** [comment]
@HazAT is there an update on this?

**Comment by HazAT** [comment]
@DanielMSchmidt The groundwork is done, native integration works.
The stacktrace merging is the only feature missing and we need to wait until we have a release of https://github.com/getsentry/raven-java/pull/381
Will talk to @bretthoerner today when he thinks when it's done.

Also we will ship stacktrace merging with a coming release since this PR is already too big.

File: android/src/main/java/io/sentry/RNSentryModule.java [hunk 2]
```diff
@@ -1,34 +1,265 @@
...
+            case 2:
+                return Level.INFO;
+            case 3:
+                return Level.ALL;
+            default:
+                return Level.OFF;
+        }
+    }
+
+    private Map<String, Object> recursivelyDeconstructReadableMap(ReadableMap readableMap) {
```
Comment (ajwhite) [inline android/src/main/java/io/sentry/RNSentryModule.java]: If this can be typed as `ReadableNativeMap`, then you can use [toHashMap](https://github.com/facebook/react-native/blob/976abf87f213eb3a05277a9956b5e582ba951a2c/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L60)

File: android/src/main/java/io/sentry/RNSentryModule.java [hunk 3]
```diff
@@ -1,34 +1,265 @@
...
+                    break;
+                default:
+                    throw new IllegalArgumentException("Could not convert object with key: " + key + ".");
+            }
+
+        }
+        return deconstructedMap;
+    }
+
+    private List<Object> recursivelyDeconstructReadableArray(ReadableArray readableArray) {
```
Comment (ajwhite) [inline android/src/main/java/io/sentry/RNSentryModule.java]: If this can be typed as `ReadableNativeArray`, then you can use [toArrayList](https://github.com/facebook/react-native/blob/976abf87f213eb3a05277a9956b5e582ba951a2c/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeArray.java#L55)

**Comment by DanielMSchmidt** [comment]
Hey @bretthoerner & @HazAT 

Sorry to bother you, but do you have an update on the timeframe of this PR? We would very much love to have this included in our app 👍

File: android/src/main/java/io/sentry/RNSentryModule.java (hunk 3 above)
Comment (ajwhite) [inline android/src/main/java/io/sentry/RNSentryModule.java]: Bumping this guy, did you want to use the existing methods from the `ReadableNativeArray` that already own this logic?

**Comment by HazAT** [comment]
Thank you guys for watching this PR so closely, we are working hard on shipping this since this is also a huge milestone for us.

If you want to help us or try it out before we ship it, you could checkout https://github.com/getsentry/raven-java/pull/381 
and call `make install` which installs sentry into you local maven.
You can also link npm to the source (see example project).

Then you should be able to try it beforehand and give feedback before we ship it.
Otherwise please be patient, we are trying to release it with as litte breaking changes as possible ...
In theory you shouldn't even notice the update besides that your errors now also have device information on android 😉

File: docs/index.rst [hunk 4]
```diff
@@ -203,6 +212,14 @@ These are functions you can call in your javascript code:
       // ---------------------------------
     }).install();
 
+    // set a callback after an event was successfully sentry
+    // its only garantueed that this event contains `event_id` & `level`
```
Comment (brentvatne) [inline docs/index.rst]: spelling: garantueed => guaranteed :)

File: lib/Sentry.js [hunk 5]
```diff
@@ -245,6 +267,7 @@ class RavenClient {
         this._dsn = dsn;
         this.options = {
             allowSecretKey: true,
+            allowDuplicates: true
```
Comment (brentvatne) [inline lib/Sentry.js]: is it intentional to change the default here?

Comment (HazAT) [inline lib/Sentry.js]: After I thought about it again I will change this to `allowDuplicates` when a native client is available otherwise we keep the default. While I was testing it was strange that only the first event was sent, even if I triggered it multiple times.

**Comment by brentvatne** [comment]
woohoo, new raven-js is released! https://github.com/getsentry/raven-js/commit/b7e98e5605c3ebcbd7ad4ca054a2485ad3e8ffd2

**Comment by DanielMSchmidt** [comment]
Yay, thanks for the hard work! 👍

**Comment by ajwhite** [comment]
Thanks folks, nicely done

**Comment by samijaber** [comment]
Amazing! My teammates and I have been patiently waiting for this to be merged to use it. Thank you so much for your hard work.

We gave it a quick spin on our project and can't seem to get Android device tags to automatically populate (like it already does for iOS). Are there manual linking steps we need to do for Android like what was needed for iOS? The guide over at https://docs.sentry.io/clients/react-native/ still doesn't mention anything about Android support.

Don't mean to sound ungrateful, just curious if I'm doing anything wrong :)

**Comment by mitsuhiko** [comment]
@samijaber the tags will only work if the native client is enabled which you can do with `react-native link react-native-sentry`. Sorry about the lack of docs at this point. We're working on it :)

In theory the link step should (assuming a recent version of the `react-native` executable) automatically patch your files.

**Comment by samijaber** [comment]
@mitsuhiko Odd. I had performed that step previously, but went ahead and re-ran `react-native link react-native-sentry` just in case. I can see that it modifies `android/app/build.gradle` and `android/settings.gradle`, but the package still falls back on `sentry-js` when it comes to Android.

I understand that these changes are <12 hours old, so I'll just sit down and patiently wait for the documentation to be updated accordingly. Thanks again!

**Comment by mitsuhiko** [comment]
@samijaber fwiw, you will need to assemble a release with gradle before the client does something on android I'm pretty sure. `./gradlew assembleRelease` should do it.

**Comment by xwartz** [comment]
@samijaber  I have the same problem, did you solve it?
